server:
  port: 9201
  servlet:
    context-path: /poli/v1
spring:
  boot:
    admin:
      client:
        url: http://localhost:9020
  application:
    name: service-user
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:customerBD;
    driver-class-name: org.h2.Driver
    platform: h2
    username: sa
    password:
