server:
  port: 9205
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9204/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-booking
          uri: lb://service-booking
          predicates:
            - Path=/poli/v1/bookings/**
        - id: service-movies
          uri: lb://service-movies
          predicates:
            - Path=/poli/v1/movies/**
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/poli/v1/users/**
        - id: service-showtimes
          uri: lb://service-showtimes
          predicates:
            - Path=/poli/v1/showtimes/**  